### ISSUE TITLE
Why don't you want to adhere to the GPL?

### ISSUE THREAD

**Issue by superjamie** [autonomous1/darkplacesrpi#17]

**Comment by autonomous1** [comment]
Who are you and why do you care?

**Comment by superjamie** [comment]
I'm a free software enthusiast who would like to see the world made a better place through open source software.

I care because my income and livelihood depend on free software licenses like the GPL.

I'd like to offer you a friendly helping hand to help you with any problems or misunderstandings or dislike that you have with the GPL.
